In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[568, 3406, 3820, 6246],
 [568, 3406, 3820, 5897],
 [568, 7923, 3820, 290],
 [6660, 581, 8548, 9647, 5140],
 [6660, 581, 8548, 9647, 928],
 [6145, 568, 3993, 3820, 8113],
 [7538, 7402, 8183, 9647]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  568 3406 3820 6246]
 [   0    0    0    0  568 3406 3820 5897]
 [   0    0    0    0  568 7923 3820  290]
 [   0    0    0 6660  581 8548 9647 5140]
 [   0    0    0 6660  581 8548 9647  928]
 [   0    0    0 6145  568 3993 3820 8113]
 [   0    0    0    0 7538 7402 8183 9647]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/mahidhargedela/Desktop/AI/.venv/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[ 0.04061041,  0.02592269, -0.00836708, -0.01811042,
         -0.0458122 , -0.03328519,  0.00998405, -0.04839853,
         -0.04852303, -0.00805988],
        [ 0.04061041,  0.02592269, -0.00836708, -0.01811042,
         -0.0458122 , -0.03328519,  0.00998405, -0.04839853,
         -0.04852303, -0.00805988],
        [ 0.04061041,  0.02592269, -0.00836708, -0.01811042,
         -0.0458122 , -0.03328519,  0.00998405, -0.04839853,
         -0.04852303, -0.00805988],
        [ 0.04061041,  0.02592269, -0.00836708, -0.01811042,
         -0.0458122 , -0.03328519,  0.00998405, -0.04839853,
         -0.04852303, -0.00805988],
        [-0.0113874 ,  0.01772687,  0.0261254 , -0.03825758,
         -0.03290415, -0.00680462,  0.0386058 ,  0.04778702,
          0.02439887, -0.02174522],
        [ 0.04171964, -0.00263466, -0.02111938, -0.02107427,
          0.03182595, -0.01457778, -0.00316788, -0.03930714,
          0.04378268, -0.00669831],
        [-0.0176368 ,  0.02304233,  0.03375972, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  568, 3406, 3820, 6246], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>